# ============================================================
# Krishi-Credit AI | app.yaml
# Databricks Apps deployment configuration
# ============================================================

command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port"
  - "8000"
  - "--server.headless"
  - "true"
  - "--server.enableCORS"
  - "false"
  - "--server.enableXsrfProtection"
  - "false"
  - "--server.address"
  - "0.0.0.0"

env:
  - name: "SARVAM_API_KEY"
    value: "sk_wzc45p0h_akTZQyjb3k77ih0zXwfibKBM"
